### ISSUE TITLE
Build目录什么用处呢？

### ISSUE THREAD

**Issue by gfreewind** [iKuaiNetworks/PPPoEPerf#3]
mkdir -p build; cmake ..; sudo make install 

这里的build目录做什么用的呢？没有也可以用啊

**Comment by xiaopeifeng** [comment]
一般cmake build为了保持目录整洁，都自建build目录。

**Comment by gfreewind** [comment]
但创建了，make后，里面也没有任何东西啊

**Comment by gfreewind** [comment]
即使改成了mkdir -p build; cd build; cmake ..; sudo make install   ，build目录同样没有用处。
另外，这个步骤少了make

**Comment by gfreewind** [comment]
重新clone的就可以，之前的即使重新做cmake ..也不行。
