### ISSUE TITLE
boost error on start , after success compile on ubuntu 16.04

### ISSUE THREAD

**Issue by jazst21** [iKuaiNetworks/PPPoEPerf#5]
boost error on start , after success compile on ubuntu 16.04

pugar@ubuntu:~ pppoe_perf --discovery
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)
pugar@ubuntu:~ uname -a
Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
pugar@ubuntu:~ 
========compiling history ==========
pugar@ubuntu:/home/Desktop$ cd PPPoEPerf
pugar@ubuntu:/home/Desktop/PPPoEPerf$ sudo mkdir -p build
pugar@ubuntu:/home/Desktop/PPPoEPerf$ cd build
pugar@ubuntu:/home/Desktop/PPPoEPerf/build$ sudo cmake ..
CMake Warning (dev) in CMakeLists.txt:
  Syntax Warning in cmake code at

    /home/Desktop/PPPoEPerf/CMakeLists.txt:28:17

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   regex
--   system
--   log_setup
--   log
--   random
--   thread
--   date_time
--   filesystem
--   chrono
--   atomic
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a (found version "1.0.2g") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Desktop/PPPoEPerf/build
pugar@ubuntu:/home/Desktop/PPPoEPerf/build$ sudo make
Scanning dependencies of target pppoe_perf
[ 25%] Building CXX object PPPoEPerf/CMakeFiles/pppoe_perf.dir/main.cpp.o
[ 50%] Building CXX object PPPoEPerf/CMakeFiles/pppoe_perf.dir/pppoe_worker.cpp.o
[ 75%] Building CXX object PPPoEPerf/CMakeFiles/pppoe_perf.dir/networker.cpp.o
[100%] Linking CXX executable ../bin/pppoe_perf
[100%] Built target pppoe_perf
pugar@ubuntu:/home/Desktop/PPPoEPerf/build$ sudo make install
[100%] Built target pppoe_perf
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/bin/pppoe_perf
-- Installing: /etc/pppoe_perf
-- Installing: /etc/pppoe_perf/conf.json
pugar@ubuntu:/home/Desktop/PPPoEPerf/build$ pppoe_perf -h
Allow options:
  -h [ --help ]              print help messages
  -c [ --config ] arg        config file
  --resend-timeout arg (=20) Specify the resend timeout
  --discovery                Only discover the PPPoE servers
  --ppp-stage                Use ppp-stage
  --terminate                Terminate the session directly
  --summary                  Show the summary stats

pugar@ubuntu:/home/Desktop/PPPoEPerf/build$ pppoe_perf -c
the required argument for option '--config' is missing
Allow options:
  -h [ --help ]              print help messages
  -c [ --config ] arg        config file
  --resend-timeout arg (=20) Specify the resend timeout
  --discovery                Only discover the PPPoE servers
  --ppp-stage                Use ppp-stage
  --terminate                Terminate the session directly
  --summary                  Show the summary stats

pugar@ubuntu:/home/Desktop/PPPoEPerf/build$ pppoe_perf --summary
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast

**Comment by xiaopeifeng** [comment]
hi, first say sorry to you, i am late; 
anyway i fix your launch bug and the cmake warning;
so pull the new code down, and just try again, any problem contact me please.
